language: java
jdk:
  - openjdk11

sudo: required

env:
  global:
    - IMAGE_NAME: gaetancollaud/fablab-manager

services:
  - docker

script:
  - mvn clean install
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t $IMAGE_NAME:$TRAVIS_BRANCH .
  - docker push $IMAGE_NAME:$TRAVIS_BRANCH
  - if [[ "$TRAVIS_TAG" != "" ]]; then docker tag $IMAGE_NAME:$TRAVIS_BRANCH $IMAGE_NAME:latest && docker push $IMAGE_NAME:latest; fi

